version: '3.8'
name: klipse

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - upload-network

  upload:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NAS_PATH=/mnt/nas
    volumes:
      - nas_volume:/mnt/nas
      - ./out:/app/out
    depends_on:
      - redis
    networks:
      - upload-network

volumes:
  redis_data:
  nas_volume:

networks:
  upload-network: