version: '3.8'
name: klipse

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - upload-network

  upload:
    build: ./upload
    ports:
      - "3005:3005"
    environment:
      - REDIS_URL=redis://redis:6379
      - NAS_PATH=/nas/klipse
    volumes:
      - nas_volume:/nas/klipse
      - ./out:/app/out
    depends_on:
      - redis
    networks:
      - upload-network

  deploy:
    build: ./deploy
    ports:
      - "3006:3006"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - nas_volume:/nas/klipse
      - nas_volume:/nas/deploy
      - nas_volume:/temp
    depends_on:
      - redis
    networks:
      - upload-network

volumes:
  redis_data:
  nas_volume:
    driver: local
    driver_opts:
      type: none
      device: ~/Desktop/projects/klipse
      o: bind

networks:
  upload-network:
