version: '3.8'
name: klipse

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - upload-network

  upload:
    build: ./upload
    ports:
      - "3005:3005"
    environment:
      - REDIS_URL=redis://redis:6379
      - NAS_PATH=/mnt/mycloud/klipse
    volumes:
      - /mnt/mycloud/klipse:/mnt/mycloud/klipse
      - ./out:/app/out
    depends_on:
      - redis
    networks:
      - upload-network

  deploy:
    build: ./deploy
    ports:
      - "3006:3006"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - /mnt/mycloud/klipse/:/nas/input
      - /mnt/mycloud/klipse/deploy/:/nas/deployments
    depends_on:
      - redis
    networks:
      - upload-network

volumes:
  redis_data:

networks:
  upload-network:
